baseURL = "https://adamblake.github.io/"
languageCode = "en-us"
title = "Adam Blake"
theme = "minimal"
googleAnalytics = ""

[params]
    author = "Adam Blake"
    description = "Thinking about thinking."
    githubUsername = "adamblake"
    accent = "#007BFF"
    backgroundColor = "#FFFFFF"
    css = [
        "https://cdn.jsdelivr.net/gh/jpswalsh/academicons/css/academicons.min.css",
        "css/style.css"
    ]
    js = [
        "js/main.js"
    ]
    favicon = "favicon.ico"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "default"
    highlightLanguages = []
    showBorder = true

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/cv/"
    name = "Curriculum Vitae"
    weight = 2

# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

[[menu.icon]]
    url = "mailto:adamblake@g.ucla.edu"
    name = "fas fa-envelope"
    weight = 1

[[menu.icon]]
    url = "https://github.com/adamblake/"
    name = "fab fa-github"
    weight = 2

[[menu.icon]]
    url = "https://www.linkedin.com/in/adamblake/"
    name = "fab fa-linkedin"
    weight = 3

[[menu.icon]]
    url = "https://scholar.google.com/citations?user=elj-XecAAAAJ&hl=en"
    name = "ai ai-google-scholar-square"
    weight = 4
